### PR TITLE
Don't split characters into bytes for processing

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes: https://github.com/RazrFalcon/roxmltree/issues/108

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
I can copy the test from https://github.com/RazrFalcon/roxmltree/issues/108, I'm just not sure where is the right place.

**Comment by WhyNotHugo** [comment]
This fixes the related issue that affects me, but I think that in general, the input shouldn't be treated as bytes but as chars, given that it's already validated utf-8.

**Comment by RazrFalcon** [comment]
I don't think this is the correct solution. You handle only the text node case. I will partially revert the old one.

**Comment by WhyNotHugo** [comment]
Yeah, I think that this is a partial solution (for my specific case), but I’m not entirely sure how to handle other cases or what those might be.

Didn’t the original commit fix a bug with \r\n ?

**Comment by RazrFalcon** [comment]
No. It was separate. And it would not be affected.

**Pull request closed without merging**
