### PR TITLE
Deduplicate tag and attribute names.

### PR DESCRIPTION
**Pull request by adamreichold**
I am not even sure this is serious as this massively trades off runtime (O(log n) search time and indirection behind `Rc`) for space.

It does reduce peak memory consumption from 7.8 GB to 5.5 GB for the document from #18 though (both of which include the 1.1 GB of reading the document itself though). Interestingly enough, `doc.names` has 17 entries in this case.

I think the search time could be reduced by using a hash table but that complicates `no_std` builds. Furthermore, both hash tables without keyed hashes and sorted slices are vulnerable to quadratic complexity DoS attacks (e.g. forcing insertion at the beginning for each parsed name).

Finally, the additional overhead of `Rc` would always be there for small documents and this opens up the additional question of using `Rc` versus `Arc`, i.e. whether `Document: Send` holds or not.

In any case, I wanted to post this for discussion even if I don't think this is really viable. But it does shed some light on the possible savings with regards to deduplication via indexes as proposed by @tomjw64 where `&[Attribute]` would have to become `impl ExactSizeIterator<Item=Attribute>` in the API.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Yes, I though about this, but I would assume performance penalty isn't worth it. Have you tried running the benchmarks?
Also, I'm not sure we even need `Rc` here. A simple index would be just fine.

As for the HashTable, it should be fine. roxmltree is no_std but it still uses `alloc`. So we have an access to HashTable.

To speed up the process we could use something like this:

```rust
fn string_hash(s: &str) -> u64 {
    let mut h = alloc::collections::hash_map::DefaultHasher::new();
    s.hash(&mut h);
    h.finish()
}

// and then

names: Vec<ExpandedNameOwned<'input>>, // stored
namesHashes: Vec<u64>, // only during parsing, sorted(?)
```

Basically a very specific kind of HashTable. 
Or even uses a custom, faster hash method. One additional dependency should be fine.

Anyway, this is a good idea as long as the performance penalty isn't that bad.

As for `Send` - I don't really care.

**Comment by adamreichold** [comment]
> As for the HashTable, it should be fine. roxmltree is no_std but it still uses alloc. So we have an access to HashTable.

As you can see at https://doc.rust-lang.org/stable/alloc/collections/index.html, the `alloc` crate does not contain a `HashMap`. This is most likely because `DefaultHasher` calls into the OS for entropy (e.g. via `getrandom`) which `alloc` cannot do. The `hashbrown` crate can be used on `no_std` though (without a runtime random key).

> Also, I'm not sure we even need Rc here. A simple index would be just fine.

I think this is the route described by

> But it does shed some light on the possible savings with regards to deduplication via indexes as proposed by @tomjw64 where &[Attribute] would have to become impl ExactSizeIterator<Item=Attribute> in the API.

meaning that e.g. an `Attribute` cannot produce its name without access to the `Document` so that it either needs a facade or the user has to manually pass `&Document` where the name is needed.

> Basically a very specific kind of HashTable.

Of course, the snippet is missing how collisions are handled which is sort of the thing which makes the difference between a good and a bad hash table.

> Anyway, this is a good idea as long as the performance penalty isn't that bad.

I think the index-based version would be nice since it does not open up the `Send` question and avoids the extra indirection in storing the `ExpandedNameOwned` structs and I would go down the benchmarks rabbit hole for that one but you seem pretty strongly opposed to that in https://github.com/RazrFalcon/roxmltree/pull/66#issuecomment-1294006135 and the following?

**Comment by RazrFalcon** [comment]
>the alloc crate does not contain a HashMap

Wow, I didn't know that.

>I think this is the route described by

Oh, my bad. 

>Of course, the snippet is missing how collisions are handled

Do you think we would be able to trigger a hash collision? I'm not an expert in this area. 
I cannot see this happening on a typical file, but someone may construct a bad one...
From my understanding, a hash collision resolving would basically require a `==` call after comparing the hash, right?

>I think the index-based version would be nice since

So an iterator type that stores `&Document` and produces `Attribute`? I guess we have no other choice...

Either way, the memory impact is too good to ignore, but performance is important as well.
We either use more memory or check every single element and attribute name for uniqueness, which seem like a performance nightmare to me.

**Comment by adamreichold** [comment]
> Either way, the memory impact is too good to ignore, but performance is important as well.
We either use more memory or check every single element and attribute name for uniqueness, which seem like a performance nightmare to me.

Yes, the impact is significant and the index-based version does not come the caveats of the `Rc`-based one, so I think that one is worth a try.

I will hopefully be able to dive into it this weekend. Or maybe @tomjw64 can propose something while I take care of benchmarking #73 now that the

> So an iterator type that stores &Document and produces Attribute? I guess we have no other choice...

is on the table again?

**Comment by RazrFalcon** [comment]
>is on the table again?

For such a big improvement - sure.

And we could replace `namespace()` with an iterator as well then. Removing `Rc` completely.

**Comment by adamreichold** [comment]
Just for completeness, this is the parsing impact of the sorted-list reference-counting version presented here:

```console
> cargo benchcmp master dedup-names 
 name              master ns/iter  dedup-names ns/iter  diff ns/iter  diff %  speedup 
 large_roxmltree   3,261,437       4,550,550               1,289,113  39.53%   x 0.72 
 medium_roxmltree  769,474         1,027,545                 258,071  33.54%   x 0.75 
 tiny_roxmltree    4,981           5,829                         848  17.02%   x 0.85 
```

Pretty gruesome, I'd say. But I'd also hope that the index-based version fears better, especially if coupled with a hash table instead of a sorted list.

**Comment by RazrFalcon** [comment]
Yes, this is expected. roxmltree is tailored towards smaller files were the current logic works just fine. You cannot have both.

Hopefully there are ways to improve uniqueness check performance.

**Pull request closed without merging**
